spring.application.name=booking-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/booking_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:booking_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
