spring.application.name=booking-service

jwt.secret=day_la_chuoi_bi_mat_ao_chi_dung_de_chay_tam_local_tren_may_toi_1234567890
jwt.expiration-ms=86400000

spring.datasource.url=jdbc:mysql://localhost:3307/booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect