spring.application.name=booking-service
jwt.secret=day_la_chuoi_bi_mat_ao_chi_dung_de_chay_tam_local_tren_may_toi_1234567890
jwt.expiration-ms=86400000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:booking_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
